name: Monopole Consulting
favicon: null
layout_spectrum: 0.731173095991835
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#37241e'
    - '#ffffff'
    - '#555150'
    - '#9a8b88'
    - '#b33831'
  brandStrength: 0.511859513586387
  lightness: 0.37537368130870163
  saturation: 0.20949318213388324
  rhythmicContrast: 0.07733757817186415
purpose: []
